title = "parameters"

[metadata]
parameter_ID = "P003 R01"

[parameters]
nav_ratio = 3
missile_vmax = 1000
target_vmax = 700
missile_amax = 30
target_amax = 7
h = 0.01
tau = 0.2

[missile]
x = 0
y = 0
theta = 30

[target]
x = 8000
y = 4000
theta = 46